//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcademyFitnessMusaeva
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public string user_name { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
        public string mail { get; set; }
        public System.DateTime birthday { get; set; }
    }
}
